import type { Resource } from '@aifs/shared';

/**
 * 英文免费资源。
 *
 * 收录标准：优先官方文档与长期维护的公开课——它们的链接存活率远高于个人博客。
 * 每一条都经过实际 HTTP 抓取核实「页面可访问且主体内容免费」，
 * 免费范围有限制（限时免费、需云账号、证书付费）的一律在 notes 里写明，
 * 不让用户点进去才发现要付费。
 */
export const EN_RESOURCES: readonly Resource[] = [
  // ============ 阶段 1：编程基础精要 ============
  {
    id: 'en-fcc-ts-handbook',
    title: 'Learn TypeScript – A Handbook for Developers',
    url: 'https://www.freecodecamp.org/news/learn-typescript-with-react-handbook/',
    provider: 'freeCodeCamp',
    language: 'en',
    difficulty: 'beginner',
    format: 'docs',
    durationHours: 3,
    topics: ['typescript', 'react', 'programming-basics'],
    stage: 'foundation',
    description:
      '免费长文手册：从类型注解、类型推断讲到联合类型、readonly、泛型与 type/interface 的区别，并用 Vite + React 项目贯穿演示。适合已经会写 JavaScript 的人快速补齐类型思维。',
    notes: '全文免费、无需注册、无付费墙，另提供中文等多语言版本；前提是已具备 JavaScript 基础。',
    verified: true,
  },
  {
    id: 'en-react-learn',
    title: 'Learn React（React 官方教程）',
    url: 'https://react.dev/learn',
    provider: 'React / Meta',
    language: 'en',
    difficulty: 'beginner',
    format: 'docs',
    durationHours: 8,
    topics: ['react', 'frontend', 'javascript', 'state-management'],
    stage: 'foundation',
    description:
      'React 官方入门教程，系统讲组件、JSX、状态管理与 Effects / 脱围机制等日常 80% 会用到的概念，页面内嵌可交互沙盒，改完立刻看到结果。',
    notes: '官方开源文档，完全免费、无需登录；内嵌沙盒可直接改代码练习。',
    verified: true,
  },
  {
    id: 'en-node-learn',
    title: 'Learn Node.js',
    url: 'https://nodejs.org/en/learn',
    provider: 'OpenJS Foundation · Node.js 官方',
    language: 'en',
    difficulty: 'beginner',
    format: 'docs',
    durationHours: 6,
    topics: ['nodejs', 'http', 'async', 'command-line', 'typescript'],
    stage: 'foundation',
    description:
      'Node.js 官方学习区：命令行与 REPL、HTTP 事务解剖、文件系统、异步与事件循环、TypeScript、测试与诊断。做后端 API 之前值得先读完「事件循环」那几节。',
    notes: '官方文档全部免费、无付费墙；页面上另有需付费的 OpenJS 认证课程，不影响本页正文学习。',
    verified: true,
  },
  {
    id: 'en-sqlbolt',
    title: 'SQLBolt – Learn SQL with simple, interactive exercises',
    url: 'https://sqlbolt.com/',
    provider: 'SQLBolt',
    language: 'en',
    difficulty: 'beginner',
    format: 'interactive',
    durationHours: 3,
    topics: ['sql', 'database', 'queries'],
    stage: 'foundation',
    description:
      '浏览器里边学边练的 SQL 入门课：18 课覆盖 SELECT、条件过滤、排序、JOIN / OUTER JOIN、聚合、查询执行顺序与建表改表。每课讲完立刻动手写查询，比看视频快得多。',
    notes: '整站免费、免注册，练习直接在浏览器内执行，无任何付费内容。',
    verified: true,
  },
  {
    id: 'en-missing-semester',
    title: 'The Missing Semester of Your CS Education',
    url: 'https://missing.csail.mit.edu/',
    provider: 'MIT CSAIL',
    language: 'en',
    difficulty: 'beginner',
    format: 'course',
    durationHours: 10,
    topics: ['cli', 'git', 'shell', 'tooling', 'debugging'],
    stage: 'foundation',
    description:
      'MIT 的「缺失的一课」，补上课堂不教的工程基本功：Shell 与命令行环境、开发环境配置、调试与性能分析、Git 版本控制、打包发布与代码质量。这一课补上，后面所有阶段都会顺很多。',
    notes: '完全免费，讲义网页与讲座视频均公开，内容以 CC BY-NC-SA 授权。',
    verified: true,
  },

  // ============ 阶段 2：LLM 应用核心 ============
  {
    id: 'en-anthropic-courses',
    title: "Anthropic's Educational Courses",
    url: 'https://github.com/anthropics/courses',
    provider: 'Anthropic',
    language: 'en',
    difficulty: 'intermediate',
    format: 'course',
    durationHours: 12,
    topics: ['llm-api', 'prompt-engineering', 'tool-calling', 'structured-output', 'streaming'],
    stage: 'llm-core',
    description:
      'Anthropic 官方开源教学仓库，5 门 Jupyter Notebook 课程依次覆盖 API 基础（密钥、模型参数、多模态、流式响应）、提示工程、真实场景提示工程、提示评估，以及用 JSON Schema 定义工具参数的工具调用。',
    notes:
      '仓库与全部 Notebook 免费开源；动手练习需自备 Anthropic API Key（官方刻意选用最低成本模型以降低学生开销）。',
    verified: true,
  },
  {
    id: 'en-dlai-prompt-eng',
    title: 'ChatGPT Prompt Engineering for Developers',
    url: 'https://www.deeplearning.ai/courses/chatgpt-prompt-eng',
    provider: 'DeepLearning.AI × OpenAI',
    language: 'en',
    difficulty: 'beginner',
    format: 'video',
    durationHours: 1.7,
    topics: ['prompt-engineering', 'llm-api'],
    stage: 'llm-core',
    description:
      '吴恩达与 OpenAI 的 Isa Fulford 主讲（9 个视频 + 7 个代码示例），用 API 动手实现摘要、推断、文本转换与扩展，并讲清提示词的两条核心原则和自定义聊天机器人的搭法。节奏极快，适合先建立整体印象。',
    notes:
      '需免费注册账号；页面写明「平台 beta 期间课程访问免费」，视频与代码示例免费，仅评分作业与结业证书需付费会员。免费标注为限时，建议定期复核；需自备 LLM API Key。',
    verified: true,
  },
  {
    id: 'en-prompting-guide',
    title: 'Prompt Engineering Guide',
    url: 'https://www.promptingguide.ai/',
    provider: 'DAIR.AI',
    language: 'en',
    difficulty: 'beginner',
    format: 'docs',
    durationHours: 8,
    topics: ['prompt-engineering', 'function-calling', 'context-management', 'rag'],
    stage: 'llm-core',
    description:
      'DAIR.AI 维护的开源提示工程教程：从 LLM 参数设置、提示要素与通用技巧，到 zero-shot / few-shot / CoT / Self-Consistency / ReAct / RAG 等主流技术，再延伸到 Function Calling 与 Context Engineering。想建立方法论而不是收集零散技巧，读这份。',
    notes: '网页版全文免费公开、无需注册或登录；站内另有付费课程，但本指南正文与 Prompt Hub 全部免费。',
    verified: true,
  },
  {
    id: 'en-ms-chat-completions',
    title: 'Work with chat completion models',
    url: 'https://learn.microsoft.com/en-us/azure/foundry/openai/how-to/chatgpt',
    provider: 'Microsoft Learn',
    language: 'en',
    difficulty: 'intermediate',
    format: 'docs',
    durationHours: 2,
    topics: ['llm-api', 'streaming', 'context-management', 'token-management', 'structured-output'],
    stage: 'llm-core',
    description:
      '微软官方教程，把 OpenAI 兼容的 Chat Completions API 讲透：system / user / assistant 消息结构与 few-shot、多轮对话循环、finish_reason 语义与流式响应、JSON 结构化输出，并用 tiktoken 统计 token、按上下文窗口裁剪历史。附 Python / .NET / JS 三套示例。',
    notes: '文档全文免费、无需登录即可阅读；运行示例需自建 Azure OpenAI 资源并按量计费，纯阅读零成本。',
    verified: true,
  },

  // ============ 阶段 3：检索增强生成 ============
  {
    id: 'en-dlai-langchain-chat',
    title: 'LangChain: Chat with Your Data',
    url: 'https://www.deeplearning.ai/courses/langchain-chat-with-your-data',
    provider: 'DeepLearning.AI',
    language: 'en',
    difficulty: 'beginner',
    format: 'video',
    durationHours: 1.3,
    topics: ['rag', 'chunking', 'embedding', 'vector-database', 'retrieval'],
    stage: 'rag',
    description:
      '由 LangChain 创始人 Harrison Chase 主讲（8 段视频 + 6 个代码示例），完整走一遍 RAG 流水线：文档加载、切分（Document Splitting）、embedding 与向量库、高级检索、问答与带记忆的聊天机器人。',
    notes:
      '需免费注册；页面写明 beta 期间课程访问免费，视频与代码示例免费，仅评分作业与证书需付费会员。需自备 LLM API Key。',
    verified: true,
  },
  {
    id: 'en-dlai-advanced-rag',
    title: 'Building and Evaluating Advanced RAG',
    url: 'https://www.deeplearning.ai/courses/building-evaluating-advanced-rag',
    provider: 'DeepLearning.AI × LlamaIndex',
    language: 'en',
    difficulty: 'intermediate',
    format: 'video',
    durationHours: 2.1,
    topics: ['rag', 'retrieval', 'reranking', 'rag-evaluation'],
    stage: 'rag',
    description:
      'Jerry Liu（LlamaIndex 创始人）主讲，讲两种明显优于基线的检索方法（sentence-window retrieval、auto-merging retrieval），以及 RAG triad 评估三件套：上下文相关性、有据可依程度、答案相关性。适合已跑通基础 RAG、想提升召回并建立评测闭环的人。',
    notes: '需免费注册；beta 期间视频与代码示例免费（页面原文声明），测验与证书需付费会员。',
    verified: true,
  },
  {
    id: 'en-ms-rag-fundamentals',
    title: 'Introduction to retrieval-augmented generation concepts',
    url: 'https://learn.microsoft.com/en-us/training/modules/rag-fundamentals/',
    provider: 'Microsoft Learn',
    language: 'en',
    difficulty: 'beginner',
    format: 'interactive',
    durationHours: 1.5,
    topics: ['rag', 'chunking', 'embedding', 'retrieval', 'rag-evaluation'],
    stage: 'rag',
    description:
      '微软官方 8 单元模块：RAG 要解决什么问题、如何为检索准备数据（切分 / 索引 / embedding）、如何检索并生成有依据的回答、如何评估与改进。含练习与单元测评，适合零基础先建立概念框架。',
    notes: 'Microsoft Learn 模块完全免费，学习、练习与测评均无需付费；动手跑通 Azure 服务需自有订阅（可选）。',
    verified: true,
  },
  {
    id: 'en-pinecone-rerankers',
    title: 'Rerankers and Two-Stage Retrieval',
    url: 'https://www.pinecone.io/learn/series/rag/rerankers/',
    provider: 'Pinecone',
    language: 'en',
    difficulty: 'intermediate',
    format: 'docs',
    durationHours: 1,
    topics: ['rag', 'reranking', 'retrieval', 'embedding'],
    stage: 'rag',
    description:
      '专门讲重排序的一章：召回率与上下文窗口的取舍、bi-encoder 与 cross-encoder 的架构差异与延迟代价、两阶段检索（先 top_k 召回再 top_n 重排）的可运行代码与最佳实践。RAG 提效性价比最高的一步就在这里。',
    notes: '全文免费阅读、无付费墙，配套 Notebook 开源；动手部分只需免费 Pinecone API key 的 Starter 额度。',
    verified: true,
  },

  // ============ 阶段 4：智能体与工具调用 ============
  {
    id: 'en-anthropic-agents',
    title: 'Building Effective Agents',
    url: 'https://www.anthropic.com/engineering/building-effective-agents',
    provider: 'Anthropic',
    language: 'en',
    difficulty: 'intermediate',
    format: 'docs',
    durationHours: 1,
    topics: ['agent', 'tool-calling', 'planning', 'multi-agent', 'workflow-orchestration'],
    stage: 'agent',
    description:
      'Anthropic 官方工程博客，区分 workflow 与 agent 两类架构，系统讲解提示链、路由、并行、orchestrator-workers、evaluator-optimizer 与自主 Agent 循环，并附工具设计（ACI）附录。核心观点是：能用简单方案解决就别上智能体。',
    notes: '完全免费公开阅读，无需注册或登录，无付费墙。',
    verified: true,
  },
  {
    id: 'en-ms-agents-beginners',
    title: 'AI Agents for Beginners（微软官方 18 课）',
    url: 'https://microsoft.github.io/ai-agents-for-beginners/',
    provider: 'Microsoft',
    language: 'en',
    difficulty: 'beginner',
    format: 'course',
    durationHours: 14,
    topics: ['agent', 'tool-calling', 'planning', 'multi-agent', 'memory', 'failure-recovery'],
    stage: 'agent',
    description:
      '微软官方入门课程，每课含讲义、短视频与代码示例，覆盖工具调用、Agentic RAG、规划模式、多智能体、元认知、记忆管理与生产部署安全。从零完整走一遍 Agent 开发全流程，这一门就够。',
    notes:
      '讲义、视频与代码全部免费开源；运行示例基于 Microsoft Agent Framework / Foundry Agent Service，需要 Azure 账号（部分示例支持其他 OpenAI 兼容的模型提供商）。',
    verified: true,
  },
  {
    id: 'en-dlai-langgraph',
    title: 'AI Agents in LangGraph',
    url: 'https://www.deeplearning.ai/courses/ai-agents-in-langgraph',
    provider: 'DeepLearning.AI × LangChain',
    language: 'en',
    difficulty: 'intermediate',
    format: 'video',
    durationHours: 1.7,
    topics: ['agent', 'tool-calling', 'planning', 'memory', 'human-in-the-loop'],
    stage: 'agent',
    description:
      '9 个视频 + 6 个代码示例：先用纯 Python 从零手写一个 Agent，再用 LangGraph 复刻同样的逻辑，讲持久化与状态管理、human-in-the-loop 与 agentic search。想真正实现可控的 Agent 循环，这门课最短路径。',
    notes: '页面标注 Enroll for Free 并写明 beta 期间免费，视频与代码示例免费；仅评分作业与证书需付费会员。需自备 LLM API Key。',
    verified: true,
  },
  {
    id: 'en-berkeley-agents-mooc',
    title: 'Large Language Model Agents MOOC（UC Berkeley）',
    url: 'https://llmagents-learning.org/f24',
    provider: 'UC Berkeley RDI',
    language: 'en',
    difficulty: 'advanced',
    format: 'video',
    durationHours: 24,
    topics: ['agent', 'planning', 'tool-calling', 'react', 'multi-agent', 'memory'],
    stage: 'agent',
    description:
      '伯克利公开课，12 讲嘉宾讲座（Google DeepMind、OpenAI、Anthropic、Meta、CMU 等）配讲义与论文清单，覆盖推理、规划与工具使用、Agent 基础设施、多智能体协作、评测与安全。偏研究向，适合想搞清楚「为什么这样设计」的进阶学习者。',
    notes: '可完全免费旁听：讲座录像、Slides、阅读材料与 quiz 全部公开，作业与证书为可选。课程学期已结束但录像仍可观看。',
    verified: true,
  },

  // ============ 阶段 5：工程化与生产 ============
  {
    id: 'en-dlai-eval-agents',
    title: 'Evaluating AI Agents',
    url: 'https://www.deeplearning.ai/courses/evaluating-ai-agents',
    provider: 'DeepLearning.AI × Arize AI',
    language: 'en',
    difficulty: 'intermediate',
    format: 'video',
    durationHours: 2.6,
    topics: ['llm-evaluation', 'observability', 'tracing', 'llm-as-a-judge'],
    stage: 'engineering',
    description:
      '动手实验式短课：从零搭一个 Agent、采集 trace 做调试、用代码与 LLM-as-a-Judge 分别评估 router 与 skill、跑结构化实验并上线监控。直击「Agent 做得对不对，怎么用数字判断」这个最难的问题。',
    notes: '页面标注 Enroll for Free 并写明 beta 期间课程免费；15 节视频 + 6 个代码示例可免费学习，仅评分作业与证书需付费会员。',
    verified: true,
  },
  {
    id: 'en-ms-genai-observability',
    title: 'Observability in generative AI',
    url: 'https://learn.microsoft.com/en-us/azure/foundry/concepts/observability',
    provider: 'Microsoft Learn',
    language: 'en',
    difficulty: 'intermediate',
    format: 'docs',
    durationHours: 2,
    topics: ['observability', 'tracing', 'llm-evaluation', 'cost-tracking', 'monitoring'],
    stage: 'engineering',
    description:
      '微软官方文档，讲生成式 AI 可观测性的三大能力（评估、监控、基于 OpenTelemetry 的分布式追踪）与 AI 应用生命周期三阶段（选模型、预生产评测、上线后监控），含 token 消耗 / 延迟 / 错误率看板、质量门禁与红队测试。',
    notes: '文档完全免费、无需登录；评估与监控功能按 Azure 消费计费，纯读文档零成本。',
    verified: true,
  },
  {
    id: 'en-aws-guardrails',
    title: 'Detect and filter harmful content with Amazon Bedrock Guardrails',
    url: 'https://docs.aws.amazon.com/bedrock/latest/userguide/guardrails.html',
    provider: 'Amazon Web Services',
    language: 'en',
    difficulty: 'intermediate',
    format: 'docs',
    durationHours: 1.5,
    topics: ['prompt-injection', 'llm-security', 'guardrails', 'safety'],
    stage: 'engineering',
    description:
      'AWS 官方文档，讲如何做内容过滤、拒绝有害话题、拦截提示词攻击（prompt attack），以及校验回答是否真的基于给定上下文。是 LLM 应用上线前做安全护栏的实用参考。',
    notes: 'AWS 官方文档免费公开阅读；实际调用 Bedrock 需 AWS 账号并按量计费，阅读学习零成本。',
    verified: true,
  },
  {
    id: 'en-litellm-routing',
    title: 'Router — Load Balancing, Fallbacks, and Retries',
    url: 'https://docs.litellm.ai/docs/routing',
    provider: 'LiteLLM（BerriAI）',
    language: 'en',
    difficulty: 'advanced',
    format: 'docs',
    durationHours: 2,
    topics: ['fallback', 'retries', 'cost-tracking', 'deployment', 'caching'],
    stage: 'engineering',
    description:
      '开源 LLM 网关 LiteLLM 的官方路由文档：多模型负载均衡、fallbacks 故障降级、超时与重试、cooldowns、按成本路由与缓存。想让 LLM 服务在上游抖动时依然可用并压住成本，这份文档是可落地的参考答案。',
    notes: '开源项目官方文档全文免费、无付费墙；跟做示例需自备模型 API Key。',
    verified: true,
  },

  // ============ 阶段 6：综合项目实战 ============
  {
    id: 'en-fcc-ai-notes',
    title: 'Build a Full Stack AI Note Taking App（Next.js + Supabase）',
    url: 'https://www.freecodecamp.org/news/build-a-full-stack-ai-note-taking-app-with-nextjs-and-supabase/',
    provider: 'freeCodeCamp',
    language: 'en',
    difficulty: 'intermediate',
    format: 'video',
    durationHours: 3,
    topics: ['capstone', 'fullstack', 'nextjs', 'database', 'llm-api', 'deployment'],
    stage: 'capstone',
    description:
      '3 小时完整项目课：Next.js App Router + Supabase（认证 / 数据库）+ Prisma + LLM API，从零做出带 AI 问答的笔记应用并部署到 Vercel。适合已会 React、想走通「前端 + 后端 + 数据库 + AI + 上线」全链路的人。',
    notes: '免费：介绍页指向 freeCodeCamp 官方 YouTube 上的完整视频，无需注册；需自备模型 API key 与 Supabase 免费账号。',
    verified: true,
  },
  {
    id: 'en-vercel-ai-sdk-rag',
    title: 'RAG Agent（Vercel AI SDK 官方指南）',
    url: 'https://ai-sdk.dev/cookbook/guides/rag-chatbot',
    provider: 'Vercel（AI SDK）',
    language: 'en',
    difficulty: 'intermediate',
    format: 'docs',
    durationHours: 3,
    topics: ['capstone', 'fullstack', 'rag', 'nextjs', 'agent', 'database'],
    stage: 'capstone',
    description:
      'Vercel 官方指南：用 Next.js App Router + AI SDK + Drizzle ORM + Postgres/pgvector 构建一个「只基于自有知识库回答」的 RAG Agent，含知识入库与检索查询。想把 RAG 真正做成产品而不是 Notebook 玩具，照着这份做。',
    notes: '官方文档全文免费开放，含配套 starter 仓库；需自备模型 API key，向量库可用免费 Postgres（如 Neon）。',
    verified: true,
  },
  {
    id: 'en-ms-genai-path',
    title: 'Develop generative AI apps in Azure',
    url: 'https://learn.microsoft.com/en-us/training/paths/develop-generative-ai-apps/',
    provider: 'Microsoft Learn',
    language: 'en',
    difficulty: 'intermediate',
    format: 'interactive',
    durationHours: 8,
    topics: ['capstone', 'fullstack', 'rag', 'agent', 'deployment', 'prompt-engineering'],
    stage: 'capstone',
    description:
      '微软官方 6 模块学习路径：模型选型与部署、开发第一个生成式 AI 应用、工具调用、用 RAG 做 grounding、性能优化与负责任 AI。适合有编程经验、想系统补齐「云上生成式 AI 应用开发」这一块的人。',
    notes: 'Microsoft Learn 全部模块免费学习（含练习与知识检查），无付费墙；动手实验需 Azure 订阅。',
    verified: true,
  },
];
